steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/indianconstitutionchatbot/IndianConstitutionChatbot.v1', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/indianconstitutionchatbot/IndianConstitutionChatbot.v1']

# Authenticate kubectl with your GKE cluster
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials constitution-cluster --zone  us-central1-a --project indianconstitutionchatbot
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=constitution-cluster'

# Apply Kubernetes deployment and service configurations
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=constitution-cluster'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/service.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=constitution-cluster'

images:
- 'gcr.io/indianconstitutionchatbot/IndianConstitutionChatbot.v1'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

  #remove